version: "3"
services:
  frontend-application:
      image: ef34962ef539
      ports:
        - "5501:80"

      depends_on:
        - backend-application

  backend-application:
   image: 0f386e286269
   #command: uvicorn app.main:app --host 127.0.0.1
   ports:
      - "8000:8000"
   networks:
      - connect
   depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
  #   volumes:
  #     - ./data:/data/db
    
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    depends_on:
      - zookeeper
  server:
    image: 1f1b6d766b30
    ports:
      - 12345:12345

  producerfile:
    image: 0177d2bde09d
    depends_on:
      - kafka

  consumerfile:
    image: 65ab7d32db9e
    depends_on:
      - kafka 

networks:
  connect:
   driver: bridge
