version: "3"
services:
 frontend:
    image: acbaab68e34e
    ports:
      - "5501:80"
    networks:
    - connect
    depends_on:
      - backend

 backend:
   image: aa92b5fd6614
   ports:
      - "8000:8000"
   networks:
      - connect
   
 server:
    image: 1f1b6d766b30
    ports:
      - 12345:12345

 zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

 kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    depends_on:
      - zookeeper

 producer:
    image: 5ef4231d0d49
    depends_on:
      kafka:
        condition: service_healthy


 consumer:
    image: ba9acb0a090e  
    depends_on:
      kafka:
        condition: service_healthy

networks:
  connect:
    driver: bridge    
